
Loading Libraries
```{r}
library(arules)
library(arulesViz)
library(dplyr)
library(tidyverse)
library(qdapTools)
library(RColorBrewer)
```
Load Data
```{r}
data <- read.csv("/Users/ks/Desktop/DDP/PREM/DATA_27APRIL2020/V1_allABCDDF.csv",header=T, na.strings=c("","[]","NA"))
```
Preprocessing into binarised data
```{r}
source("preprocessing.R")
redundant_cols <- c('X' , 'Unnamed..0' , 'No' , 'X_id' , 'form' , 'owner' , 'Type', 'createdOn', 'Patient.ID' , 'Patient.name', 'Unnamed..71')
col_length <- length(colnames(data))

data <- basic_preproc(data, redundant_cols)

redundant_cols <- c("Version","District","hospital.name","Year","Month","Date","Referred.Out.Institute.Name","Reason.For.Referal","Time.of.Arrival","Time.of.first.treatment","Time.of.transfer")
binarised_data <- disease_preproc(data, redundant_cols)
#While splitting columns the columns with redundant names like "NIL", "NO","FALSE" manually. Check the preprocessing file with disease_preproc function
```

Data subsets
```{r}
ABCDtreatment <- binarised_data %>%
          select(c("Airway","Breathing","Circulation","Disability","Head.Tilt.Chin.Lift" ,"Bag.valve.Mask.Ventilation","CPAP", "Intubation", colnames(bronchodialators), "Cardiac.Massage", "Normal.Saline.Bolus", colnames(inotrope), "X25..Dextrose", colnames(anti.Fit.Medication)))

comorbidities <- binarised_data %>%
                        select(c(colnames(cardiac), colnames(CNS), colnames(RS),"Renal.Disease" ,"Liver.Disease", "Blood" , "Metabolic",  "Post.Surgical" , "Bottle.Fed" , "Poor.child.rearing.practices" , "PLHA")) %>% mutate_all(funs(as.numeric(.)))
comorbidities$Renal.Disease = comorbidities$Renal.Disease-1
comorbidities$Liver.Disease = comorbidities$Liver.Disease-1
comorbidities$Blood = comorbidities$Blood-1
comorbidities$Post.Surgical = comorbidities$Post.Surgical-1
comorbidities$Metabolic = comorbidities$Metabolic-1
comorbidities$Bottle.Fed = comorbidities$Bottle.Fed-1
comorbidities$Poor.child.rearing.practices = comorbidities$Poor.child.rearing.practices-1
comorbidities$PLHA = comorbidities$PLHA -1
comorbidities <- comorbidities %>% mutate_all(funs(as.logical(.)))

ABCD <- binarised_data %>% select(c("Airway", "Breathing", "Circulation", "Disability"))
```


Frequency plot-Etiology
```{r}

etiology <- as(etiology, "transactions")
a = itemFrequencyPlot(etiology,topN=20,type="absolute",col=brewer.pal(8,'Pastel2'), main="Etiology frequency", xlab = "Etiology", ylab = "")



```

```{r}

rule1_etiology <- apriori(etiology, parameter = list(support = 0.001, confidence = 0.1,minlen = 1, maxlen = 3))
a = inspect(head(sort(rule1_etiology, by='lift'),6))
is.dbl <- sapply(a, is.double)
a[is.dbl] <- lapply(a[is.dbl], round, 4)
write.csv(a, "/Users/ks/Desktop/DDP/PREM/Analysis/AprioriEtiology.csv")
```


```{r}
plot(rule1_etiology)

```

```{r}
plot(rule1_etiology, method = 'grouped')
```

```{r}
plotly_arules(rule1_etiology)

```

```{r}
como <- as(comorbidities, "transactions")
itemFrequencyPlot(como,topN=20,type="absolute",col=brewer.pal(8,'Pastel2'), main="Comorbidities Frequency", xlab = "Comorbidities", ylab = "")
```

```{r}
rule1_como <- apriori(como, parameter = list(support = 0.001, confidence = 0.01, maxlen = ncol(como)))
```


```{r}
a = inspect(head(sort(rule1_como, by = "lift"), 6))
is.dbl <- sapply(a, is.double)
a[is.dbl] <- lapply(a[is.dbl], round, 4)
write.csv(a, "/Users/ks/Desktop/DDP/PREM/Analysis/AprioriComorbidities.csv")
```

```{r}
plot(rule1_como)
```

```{r}
plot(rule1_como, method = 'grouped')
```

```{r}
plotly_arules(rule1_como)

```

```{r}
outComo <- binarised_data %>%
           select(c(colnames(comorbidities), "Outcome"))
outComo <- cbind(outComo, mtabulate(outComo$Outcome)) %>%
           select(-c("Outcome"))
oC <- as(outComo, "transactions")
rule1_oC <- apriori(oC, parameter = list(support = 0.01, confidence = 0.1), appearance = list(default="lhs",rhs="Admitted"), control = list (verbose=F))

inspect(head(sort(rule1_oC, by='lift'),10))
#is.dbl <- sapply(a, is.double)
#a[is.dbl] <- lapply(a[is.dbl], round, 4)
#write.csv(a, "/Users/ks/Desktop/DDP/PREM/Analysis/AprioriEtiology.csv")

```

